version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: "docker"
    directory: "/tutor/templates/build/openedx"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: "docker"
    directory: "/tutor/templates/build/permissions"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
