apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: http-port
    - port: 443
      protocol: TCP
      name: https
      targetPort: https-port
  selector:
    app: nginx
