apiVersion: v1
kind: Service
metadata:
  name: openedx
spec:
  type: NodePort
  ports:
    - port: 8000
      protocol: TCP
  selector:
    # TODO different services and names for lms/cms
    app: openedx
