apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: clean-openedx-staticfiles
          image: regis/openedx:hawthorn
          command: ['rm', '-rf', '/var/www/openedx/staticfiles']
          volumeMounts:
            - mountPath: /var/www/openedx/
              name: openedx-staticfiles
          imagePullPolicy: Always
        - name: init-openedx-staticfiles
          image: regis/openedx:hawthorn
          command: ['cp', '-r', '/openedx/staticfiles', '/var/www/openedx/']
          volumeMounts:
            - mountPath: /var/www/openedx/
              name: openedx-staticfiles
          imagePullPolicy: Always
      containers:
        - name: nginx
          image: nginx:1.13
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: config
            - mountPath: /var/www/openedx/
              name: openedx-staticfiles
            - mountPath: /openedx/data/lms
              name: data
          ports:
            - containerPort: 80
              name: http-port
            - containerPort: 443
              name: https-port
      volumes:
        - name: config
          configMap:
            name: nginx-config
        - name: openedx-staticfiles
          persistentVolumeClaim:
            claimName: openedx-staticfiles
        - name: data
          persistentVolumeClaim:
            claimName: lms-data
