from .production_common import *

ALLOWED_HOSTS = [
    ENV_TOKENS.get('LMS_BASE'),
    FEATURES['PREVIEW_LMS_BASE'],
]

DEFAULT_FROM_EMAIL = 'registration@' + ENV_TOKENS['LMS_BASE']
DEFAULT_FEEDBACK_EMAIL = 'feedback@' + ENV_TOKENS['LMS_BASE']
SERVER_EMAIL = 'devops@' + ENV_TOKENS['LMS_BASE']
TECH_SUPPORT_EMAIL = 'technical@' + ENV_TOKENS['LMS_BASE']
CONTACT_EMAIL = 'info@' + ENV_TOKENS['LMS_BASE']
BUGS_EMAIL = 'bugs@' + ENV_TOKENS['LMS_BASE']
UNIVERSITY_EMAIL = 'university@' + ENV_TOKENS['LMS_BASE']
PRESS_EMAIL = 'press@' + ENV_TOKENS['LMS_BASE']
PAYMENT_SUPPORT_EMAIL = 'payment@' + ENV_TOKENS['LMS_BASE']
BULK_EMAIL_DEFAULT_FROM_EMAIL = 'no-reply@' + ENV_TOKENS['LMS_BASE']
API_ACCESS_MANAGER_EMAIL = 'api-access@' + ENV_TOKENS['LMS_BASE']
API_ACCESS_FROM_EMAIL = 'api-requests@' + ENV_TOKENS['LMS_BASE']
